py2hwsw/__init__.py
setup.py

Missing correct email and license

Create PIP installable module

---

.github/workflows/ci.yml
py2hwsw/scripts/iob_snippet.py
py2hwsw/scripts/py2hwsw.py

New regex expressions seem to be more accurate and avoid having to search for exceptions.

Improve regex expressions

---

.github/workflows/ci.yml
py2hwsw/scripts/block_gen.py
py2hwsw/scripts/config_gen.py
py2hwsw/scripts/csr_gen.py
py2hwsw/scripts/if_gen.py
py2hwsw/scripts/iob_core.py
py2hwsw/scripts/iob_port.py
py2hwsw/scripts/iob_wire.py
py2hwsw/scripts/py2hwsw.py
py2hwsw/scripts/reg_gen.py
py2hwsw/scripts/wire_gen.py

This version was used for PR: https://github.com/IObundle/iob-soc/pull/884

General improvements

---

py2hwsw/lib/hardware/arith_logic/iob_int_sqrt/iob_int_sqrt.py
py2hwsw/lib/hardware/basic_tests/iob_fsm_defaults/iob_fsm_defaults.py
py2hwsw/lib/hardware/csrs/csrs.py
py2hwsw/scripts/iob_core.py
py2hwsw/scripts/iob_fsm.py
py2hwsw/scripts/iob_snippet.py
py2hwsw/scripts/py2hwsw.py

This PR includes changes from https://github.com/IObundle/py2hwsw/pull/31. That one should be merged first.
- Add new standard python parameters: 3e247a0ce9c29cde4cbecfd85dd6ea957afc6c52
- Add `print_core_dict` target: 1b71af5c06333e63ea247bad0dc6511d10bf2746

Add new standard python parameters; Add `print_core_dict` target.

---

py2hwsw/lib/hardware/csrs/csrs.py
py2hwsw/lib/hardware/csrs/scripts/csr_gen.py
py2hwsw/lib/hardware/csrs/scripts/reg_gen.py
py2hwsw/scripts/block_gen.py
py2hwsw/scripts/py2hwsw.py

Related to PR https://github.com/IObundle/iob-soc/pull/929

Improve `csrs` module.

---

py2hwsw/hardware/fpga/Makefile
py2hwsw/hardware/fpga/quartus/build.tcl
py2hwsw/hardware/fpga/vivado/build.tcl

Used in PR https://github.com/IObundle/iob-soc/pull/936

Rename default `$(FPGA_TOP)` value and constraints

---

py2hwsw/scripts/param_gen.py

This should solve issue IObundle/iob-soc#837

Validate that parameter values fit within the specified range

---

py2hwsw/docker/Dockerfile
py2hwsw/docker/Makefile
py2hwsw/docker/README.md
py2hwsw/py2hwsw_document/document/tsrc/how.tex
py2hwsw/py2hwsw_document/document/tsrc/iob_and.tex
py2hwsw/py2hwsw_document/document/tsrc/problem.tex
py2hwsw/py2hwsw_document/document/tsrc/purpose.tex
py2hwsw/py2hwsw_document/document/tsrc/setup_build.tex
py2hwsw/py2hwsw_document/document/tsrc/ug.tex

- ug improvements
- improve text
- fix lstlistings
- fix commands in iob-soc tutorial
- initial docker
- dockerfile for a clean environment with ubuntu and nix package manager installed
- add simple makefile targets and readme for instructions

feat(docs, docker): ug improvements,initial docker

---

.github/workflows/docker-image.yml
py2hwsw/docker/Dockerfile
py2hwsw/docker/README.md

- add github actions workflow to build and publish docker image on each release
- update docker README instructions
- update dockerfile to install py2hwsw dependencies

feat(docker): workflow to build and publish image

---

py2hwsw/lib/hardware/memories/ram/iob_ram_at2p/iob_ram_at2p.py
py2hwsw/lib/hardware/memories/ram/iob_ram_atdp/iob_ram_atdp.py
py2hwsw/lib/hardware/memories/ram/iob_ram_atdp_be/iob_ram_atdp_be.py
py2hwsw/lib/hardware/memories/ram/iob_ram_sp/iob_ram_sp.py
py2hwsw/lib/hardware/memories/ram/iob_ram_sp_be/iob_ram_sp_be.py
py2hwsw/lib/hardware/memories/ram/iob_ram_sp_se/iob_ram_sp_se.py
py2hwsw/lib/hardware/memories/ram/iob_ram_t2p/iob_ram_t2p.py
py2hwsw/lib/hardware/memories/ram/iob_ram_t2p_be/iob_ram_t2p_be.py
py2hwsw/lib/hardware/memories/ram/iob_ram_tdp/iob_ram_tdp.py
py2hwsw/lib/hardware/memories/ram/iob_ram_tdp_be_xil/iob_ram_tdp_be_xil.py
py2hwsw/lib/hardware/memories/rom/iob_rom_atdp/iob_rom_atdp.py
py2hwsw/lib/hardware/memories/rom/iob_rom_sp/iob_rom_sp.py
py2hwsw/lib/hardware/memories/rom/iob_rom_tdp/iob_rom_tdp.py

- addresses IObundle/py2hwsw#95

fix(mem): generate if for RAMS when HEXFILE="none"

---

py2hwsw/hardware/fpga/Makefile
py2hwsw/hardware/simulation/Makefile
py2hwsw/lib/hardware/iob_system/scripts/iob_system_utils.py
py2hwsw/lib/hardware/iob_system/software/src/iob_system_firmware.c
py2hwsw/lib/hardware/iob_system/submodules/TESTER/software/src/iob_system_firmware.c
py2hwsw/scripts/config_gen.py

Use the following command to build the `iob_system` and run the Tester in simulation:
```
nix-shell py2hwsw/lib/ --run "make -C py2hwsw/lib sim-build CORE=iob_system && make -C ../iob_system_V0.7/submodules/tester/ sim-run"
```

Add Tester for `iob_system`

---

py2hwsw/hardware/fpga/Makefile
py2hwsw/hardware/fpga/quartus/build.tcl
py2hwsw/hardware/lint/spyglass.mk
py2hwsw/lib/hardware/arith_logic/iob_prio_enc/iob_prio_enc.py
py2hwsw/lib/hardware/buses/iob_axi2iob/hardware/src/iob_axi2iob.v
py2hwsw/lib/hardware/iob_csrs/iob_csrs.py
py2hwsw/lib/hardware/iob_csrs/scripts/csr_gen.py
py2hwsw/lib/hardware/memories/iob_axi_ram/hardware/src/iob_axi_ram.v
py2hwsw/lib/iob_system/hardware/fpga/quartus/cyclonev_gt_dk/board.mk
py2hwsw/lib/iob_system/hardware/modules/iob_system_mwrap/iob_system_mwrap.py
py2hwsw/lib/iob_system/iob_system.py
py2hwsw/lib/iob_system/submodules/BOOTROM/iob_bootrom.py
py2hwsw/scripts/console.py

- Fix `iob_system` verilog warnings reported by Quartus. Resolves #128.
- Add debug mode to console.
- Add default value `/dev/usb-uart` for `BOARD_SERIAL_PORT` Makefile variable.

Fix `iob_system` verilog warnings reported by Quartus. 

---

py2hwsw/document/Makefile
py2hwsw/document/tsrc/ug.tex
py2hwsw/lib/hardware/memories/iob_memwrapper/iob_memwrapper.py

Add "Memories" subsection in user guide

---

py2hwsw/scripts/block_gen.py
py2hwsw/scripts/if_gen.py

Additionally, both ports/wires must be if_gen interfaces to be connected by name

iob_clk only generates clk signal if params=''" and clk_en_rst if params is not passed

---

py2hwsw/lib/hardware/arith_logic/div/iob_div_subshift/iob_div_subshift.py
py2hwsw/lib/hardware/arith_logic/div/iob_div_subshift_frac/iob_div_subshift_frac.py
py2hwsw/lib/hardware/arith_logic/iob_int_sqrt/iob_int_sqrt.py
py2hwsw/lib/hardware/basic_tests/iob_2to1mux/iob_2to1mux.json
py2hwsw/lib/hardware/basic_tests/iob_2to1mux/iob_2to1mux.py
py2hwsw/lib/hardware/basic_tests/iob_fsm3/iob_fsm3.py
py2hwsw/lib/hardware/basic_tests/iob_fsm_defaults/iob_fsm_defaults.py
py2hwsw/lib/hardware/basic_tests/iob_rom_acc/iob_rom_acc.py
py2hwsw/scripts/iob_comb.py
py2hwsw/scripts/iob_fsm.py

This PR applies the changes in https://github.com/IObundle/py2hwsw/issues/151

Change fsm and comb dict keys

---

py2hwsw/lib/hardware/clocks_resets/iob_pulse_gen/iob_pulse_gen_tester/iob_pulse_gen_tester.py
py2hwsw/lib/hardware/clocks_resets/iob_pulse_gen/iob_pulse_gen_tester/software/src/iob_pulse_gen_tester_firmware.c
py2hwsw/lib/hardware/clocks_resets/iob_pulse_gen/iob_pulse_gen_tester/software/src/iob_system_firmware.c
py2hwsw/lib/hardware/iob_csrs/iob_csrs.py
py2hwsw/lib/hardware/iob_csrs/scripts/csr_classes.py
py2hwsw/lib/hardware/iob_csrs/scripts/reg_gen.py
py2hwsw/lib/iob_system/iob_system.py
py2hwsw/lib/iob_system/iob_system_tester/iob_system_tester.py
py2hwsw/lib/iob_system/iob_system_tester/software/src/iob_system_tester_firmware.c
py2hwsw/lib/iob_system/scripts/iob_system_utils.py
py2hwsw/lib/peripherals/iob_gpio/README.md
py2hwsw/lib/peripherals/iob_uart/iob_uart.py
py2hwsw/lib/peripherals/iob_uart/iob_uart_tester/iob_uart_tester.py
py2hwsw/lib/peripherals/iob_uart/iob_uart_tester/software/src/iob_uart_tester_firmware.c
py2hwsw/scripts/iob_core.py

- Fix tester bugs.
- Fix firmware name of iob_pulse_gen and iob_system testers.
- Add tester to iob_uart. Resolves #195

Fix tester bugs; Add tester to iob_uart; Update pulse_gen and iob_system testers.

---

py2hwsw/docker/Dockerfile
py2hwsw/lib/hardware/memories/ram/iob_ram_2p/iob_ram_2p.py
py2hwsw/lib/hardware/memories/rom/iob_rom_atdp/iob_rom_atdp.py
py2hwsw/lib/hardware/memories/rom/iob_rom_sp/iob_rom_sp.py
py2hwsw/lib/hardware/memories/rom/iob_rom_tdp/iob_rom_tdp.py
py2hwsw/lib/iob_system/iob_system.py
py2hwsw/scripts/if_gen.py

Includes changes form PR https://github.com/IObundle/py2hwsw/pull/201. That one should be merged first.

Fix memories

---

py2hwsw/docker/Dockerfile
py2hwsw/lib/hardware/memories/ram/iob_ram_2p/iob_ram_2p.py
py2hwsw/lib/hardware/memories/rom/iob_rom_sp/iob_rom_sp.py
py2hwsw/scripts/if_gen.py

- reduce docker image size
- update ram 2p with standard ram 2p ports
- fix r_data port from if_gen from output reg to output
- update rom-sp snippet

fix(docker, mem): reduce docker image size, standard 2p ports, fix rdata port

---

py2hwsw/scripts/if_gen.py
py2hwsw/scripts/ipxact_gen.py

Also added VLNV information to each interface of `if_gen.py` for use in IP-XACT/documentation.

Generate IP-XACT ports and bus interfaces of cores

---

py2hwsw/lib/hardware/buses/iob_axis2axi/submodules/iob_axis2axi_wr/hardware/src/iob_axis2axi_wr_int.v

- update axis2axi with ac97 fixes

feat(axis2axi): update with ac97 fixes

---

py2hwsw/hardware/simulation/Makefile
py2hwsw/hardware/simulation/src/iob_v_tb.v
py2hwsw/lib/Makefile
py2hwsw/lib/default.nix
py2hwsw/lib/hardware/memories/iob_memwrapper/iob_memwrapper.py
py2hwsw/lib/hardware/registers/iob_reg/iob_reg.py
py2hwsw/lib/iob_system/hardware/fpga/quartus/iob_cyclonev_gt_dk/board.mk
py2hwsw/lib/iob_system/hardware/fpga/vivado/iob_aes_ku040_db_g/board.tcl
py2hwsw/lib/iob_system/software/src/iob_core_tb.c
py2hwsw/lib/iob_system/software/src/iob_system_firmware.c
py2hwsw/lib/peripherals/iob_axistream_in/software/src/iob_axistream_in_swreg_pc_emul.c
py2hwsw/lib/peripherals/iob_axistream_out/software/src/iob_axistream_out_swreg_pc_emul.c
py2hwsw/lib/peripherals/iob_nco/software/src/iob_nco_csrs_pc_emul.c
py2hwsw/lib/peripherals/iob_timer/software/src/iob_timer_csrs_pc_emul.c
py2hwsw/lib/peripherals/iob_uart/software/src/iob_uart_csrs_pc_emul.c
py2hwsw/scripts/board_client.py
py2hwsw/software/src/iob_c_tb.c
tmp/iob_uart_fsm/software/src/iob_uart_csrs_pc_emul.c

- Launch 'tb' process via board_client. Resolves #227.
- Use named pipe to communicate from V to C, to improve ￼efficiency of universal test bench.
- Add missing jre dependency for libreoffice of nix environment. Should resolve #213
- Fix iob_system flows
- Fix iob_reg for Quartus [15b0d5e](https://github.com/IObundle/py2hwsw/pull/231/commits/15b0d5ec6488815efc8b81b7340c91f975d41a3f)

Resolve py2 issues; Improve vutb.

---

py2hwsw/scripts/iob_comb.py
py2hwsw/scripts/iob_fsm.py

Change wires to reg if used on the left-hand side in "comb"
Resolves https://github.com/IObundle/py2hwsw/issues/263

Fix set needed reg

---

py2hwsw/scripts/iob_comb.py

The last commit didn't fully solve the issue. This commit should deliver the intended behaviour in iob_comb.

Fix reg usage in iob_comb

---

py2hwsw/lib/hardware/iob_csrs/scripts/csr_gen.py

- remove duplicated `ready_i` port for RW noauto regs

fix(csrs): duplicated ready port for RW noauto

---

py2hwsw/document/tsrc/deliverables.tex
py2hwsw/lib/hardware/iob_csrs/scripts/csr_gen.py
py2hwsw/lib/hardware/memories/iob_memwrapper/iob_memwrapper.py
py2hwsw/py2hwsw_document/document/tsrc/standard_interfaces.tex
py2hwsw/scripts/block_gen.py
py2hwsw/scripts/config_gen.py
py2hwsw/scripts/doc_gen.py
py2hwsw/scripts/io_gen.py

Includes changes from iob-soc/fixasrc up to commit: [131c041e6f7a0bb47d764528a65c026516760b1b](https://github.com/IObundle/iob-soc/tree/131c041e6f7a0bb47d764528a65c026516760b1b)
Resolves #261
Related to #141

Update py2hwsw with new version of iob-soc/fixasrc 

---

py2hwsw/lib/hardware/iob_csrs/scripts/csr_gen.py
py2hwsw/scripts/block_gen.py
py2hwsw/scripts/config_gen.py
py2hwsw/scripts/io_gen.py
py2hwsw/scripts/iob_conf.py
py2hwsw/scripts/iob_instance.py
py2hwsw/scripts/iob_wire.py
py2hwsw/scripts/ipxact_gen.py
py2hwsw/scripts/wire_gen.py

- update py2hwsw with changes from iob-soc/fixasrc
- Includes changes up to commit: 21b0ccbae7d2adbe83c1b560e01487b30ecca909
- Related to https://github.com/IObundle/py2hwsw/issues/141
- remove `if_defined` and `if_not_defined` attributes from py2
- addresses https://github.com/IObundle/py2hwsw/issues/317

feat(py2): update with iob-soc/fixasrc changes; remove `if_[not_]defined` 

---

py2hwsw/scripts/user_api/api.py

help(api) will show this description.

wip(api): Add 'bla bla bla' description.

---

py2hwsw/lib/hardware/basic_tests/iob_aoi/iob_aoi.py
py2hwsw/lib/hardware/basic_tests/iob_inv/iob_inv.py
py2hwsw/lib/hardware/basic_tests/iob_or/iob_or.py
py2hwsw/scripts/block_gen.py
py2hwsw/scripts/bus_gen.py
py2hwsw/scripts/iob_core.py
py2hwsw/scripts/iob_instance.py
py2hwsw/scripts/iob_port.py
py2hwsw/scripts/iob_portmap.py
py2hwsw/scripts/iob_wire.py
py2hwsw/scripts/param_gen.py

- fix instance usage
- update port / wire details with global wires
- still needs work with block gen handling ports and buses

wip(aoi): progress in aoi setup

---

py2hwsw/lib/hardware/buses/iob_axis_s_axi_m/iob_axis_s_axi_m.py
py2hwsw/lib/iob_system/iob_system.py
py2hwsw/scripts/iob_conf.py
py2hwsw/scripts/iob_core.py
py2hwsw/scripts/param_gen.py
py2hwsw/scripts/user_api/api.py
py2hwsw/scripts/verilog_gen.py

Adds support for confs of kind 'L". Local parameters do not appear in documentation.
Will resolve issue https://github.com/IObundle/py2hwsw/issues/331

feat(confs): Add support for local parameters

---

py2hwsw/lib/hardware/arith_logic/div/iob_div_subshift/hardware/simulation/src/iob_div_subshift_tb.v
py2hwsw/lib/hardware/arith_logic/div/iob_div_subshift/iob_div_subshift.py
py2hwsw/lib/hardware/arith_logic/div/iob_div_subshift_frac/hardware/simulation/src/iob_div_subshift_frac_tb.v
py2hwsw/lib/hardware/arith_logic/div/iob_div_subshift_frac/iob_div_subshift_frac.py
py2hwsw/lib/hardware/arith_logic/iob_fp/iob_fp_div/hardware/src/iob_fp_div.v
py2hwsw/lib/hardware/registers/regarray/iob_regarray_at2p/iob_regarray_at2p.py

- update py2hwsw with `iob-soc-int` until commit: `1f95bee06b`
- addresses #141

feat(div): add synchronous reset to div subshift

---

py2hwsw/lib/default.nix

- update nixpkgs to use newer version for verilator with this coverage fix: https://github.com/verilator/verilator/issues/5473

feat(nix): bump nixpkgs to 25.05
