IObundle/py2hwsw

py2hwsw/scripts/iob_base.py
py2hwsw/scripts/iob_wire.py

This PR modifies the `create_wire()` method to automatically create signal references if more than one signal have the same name. 
For example, if multiple wires/ports have a signal with the same name, then, one of them will be the original signal and the others will be references to it.
Also fixed handling of `signal` lists by the `find_obj_in_list()` function.

Auto-create signal references

---

.github/workflows/ci.yml

- Add test that tries to run py2hwsw on all examples. It just prints the build directory of example modules, but will fail if there are python syntax errors.
- Add test that clones iob-soc/if_gen2 lib directory and runs tests for all modules using the py2hwsw version of this repo.

feat(ci): Add github actions tests

---

py2hwsw/scripts/iob_fsm.py
py2hwsw/scripts/iob_snippet.py

To use a for loop in an FSM there must be a state with the loop described in front of its tag:
`<tag>: for(<init statement>;<condition statement>;<update statement>)`
The end of the loop must be marked with the same tag with '_endfor' as a suffix:
`<tag>_endfor:`
The 'init statement' will be added to the beginning of the 'tag' state
To the end of the 'tag_endfor' state, the 'update statement will be added followed by
`if (condition statement) begin
pc_nxt = tag;
end`

Add support for for loops in iob_fsms

---

.github/workflows/ci.yml
py2hwsw/document/Makefile
py2hwsw/document/tsrc/pb.tex
py2hwsw/document/tsrc/rn.tex
py2hwsw/document/tsrc/ug.tex
py2hwsw/lib/hardware/csrs/csrs.py
py2hwsw/lib/hardware/csrs/scripts/csr_gen.py
py2hwsw/scripts/py2hwsw.py

Included in PR: https://github.com/IObundle/iob-soc/pull/940
- Update `ci.yml` to use iob-soc's new `PY2HWSW_PATH` environment variable. This commit fixes issues with py2hwsw not using the correct version for iob-soc/lib test.
- Add missing regs in csrs module (no longer infered).
- Add new makefile (build) variable [`SECTIONCLEARPAGE`](https://github.com/IObundle/py2hwsw/pull/44/files#diff-8478c66c70610d60b5fea9990f2f04be7f600be331eab03f03c715d2ac883c57R95) to select if should insert an optional clearpage after each doc section.
Update documents to include optional clearpage. This should resolve https://github.com/IObundle/py2hwsw/issues/7.
- Add new python parameter [`interrupt_csrs`](https://github.com/IObundle/py2hwsw/pull/44/files#diff-1897540fd1ab2ff5673e78b2187b38657ea28a275f578088f …

FIx ci.yml; Add missing regs in csrs module; Resolve issues.

---

py2hwsw/lib/hardware/arith_logic/iob_int_sqrt/iob_int_sqrt.py
py2hwsw/scripts/iob_base.py
py2hwsw/scripts/iob_conf.py

Shorthand notation now resembles the command line by using flags instead of $<letter>
The description is mandatory and always starts on the second line and can take multiple lines
iob_int_sqrt has its confs described with the new notation and can be seen as an example

Shorthand notation changed to look like command line

---

.github/workflows/ci.yml
py2hwsw/lib/hardware/csrs/csrs.py
py2hwsw/lib/hardware/csrs/scripts/csr_gen.py
py2hwsw/lib/hardware/csrs/scripts/fifos.py
py2hwsw/scripts/block_gen.py
py2hwsw/scripts/iob_core.py
py2hwsw/scripts/py2hwsw.py
py2hwsw/software/Makefile

Included in PR https://github.com/IObundle/iob-soc/pull/945

Generate internal CSR FIFOS (via python params); Add CSRs APB, AXI, AXIL support; Remove default pc-emul sources.

---

py2hwsw/scripts/console.py

implement serial read with bytestring list and concatenate all bytes at the end. 
This implementation is better for large file since the original code: 
```python 
data += byte 
``` 
becomes progressively slower for large bytestrings. 
Python allocates a new space for the result string and copies both strings into it. 
This becomes so slow that the console misses some bytes sent by IOB-SOC at around ~1MB bytestrings.

fix(console): faster serial read

---

py2hwsw/hardware/simulation/questa.mk

- update `questa.mk` `clean` target to match other `SIMULATOR.mk` targets

fix(questa): clean target calls gen-clean

---

py2hwsw/lib/hardware/buses/iob_address_translator/iob_address_translator.py
py2hwsw/lib/hardware/iob_csrs/scripts/csr_gen.py
py2hwsw/lib/hardware/iob_system/hardware/simulation/iob_system_sim.py
py2hwsw/lib/hardware/iob_system/iob_system.py
py2hwsw/lib/hardware/iob_system/scripts/iob_system_utils.py

New `iob_address_translator` module translates addresses based on configurable memory zones.
Each memory zone is configured by a python tuple with three elements:
1) Start address of the zone.
2) End address of the zone (inclusive).
3) Offset to sum with the original address, in order to translate it to the new address space.
If the master tries to access an address in a memory zone, the translation will be applied by summing the corresponding offset.
Otherwise, no translation is applied.
Example with 3 memory zones:
```Python
{
"core_name": "iob_address_translator",
"instance_name": "address_translator",
"instance_description": "Translate addresses to access memory zones",
"parameters": {
"ID_W": "AXI_ID_W",
"ADDR_W": params["addr_w"] - 2,
"DATA_W": params["data_w"],
"LEN_W": …
```

Add `iob_address_translator` module.

---

py2hwsw/lib/hardware/iob_csrs/scripts/csr_gen.py

Resolves issue https://github.com/IObundle/py2hwsw/issues/109

CSRs: Remove `iob_ready` dependency for `ren`/`wen` signals with `autoreg=False`

---

py2hwsw/scripts/iob_core.py

Deprecate `setup` (nosetup) attribute as mentioned here: https://github.com/IObundle/py2hwsw/issues/101#issuecomment-2515830839
This commit, along with PR https://github.com/IObundle/py2hwsw/pull/106, resolves #101.

Remove `setup` attribute.

---

py2hwsw/lib/hardware/basic_tests/iob_csrs_demo/hardware/simulation/src/iob_csrs_demo_tb.v
py2hwsw/lib/hardware/basic_tests/iob_csrs_demo/iob_csrs_demo.py
py2hwsw/lib/iob_system/hardware/simulation/iob_system_sim.py
py2hwsw/lib/iob_system/iob_system.py
py2hwsw/lib/iob_system/scripts/iob_system_utils.py
py2hwsw/lib/iob_system/submodules/BOOTROM/iob_bootrom.py
py2hwsw/lib/peripherals/iob_axistream_in/iob_axistream_in.py
py2hwsw/lib/peripherals/iob_axistream_out/iob_axistream_out.py
py2hwsw/lib/peripherals/iob_gpio/iob_gpio.py
py2hwsw/lib/peripherals/iob_nco/hardware/simulation/src/iob_nco_tb.v
py2hwsw/lib/peripherals/iob_nco/iob_nco.py
py2hwsw/lib/peripherals/iob_regfileif/iob_regfileif.py
py2hwsw/lib/peripherals/iob_timer/iob_timer.py
py2hwsw/lib/peripherals/iob_uart/hardware/simulation/src/iob_uart_tb.cpp
py2hwsw/lib/peripherals/iob_uart/iob_uart.py
py2hwsw/scripts/iob_core.py

Renamed port from `<corename>_cbus_s` to `iob_csrs_cbus_s`. Resolves https://github.com/IObundle/py2hwsw/issues/145

feat(csrs): Rename cbus port to remove corename from prefix.

---

py2hwsw/scripts/iob_core.py

This solves https://github.com/IObundle/py2hwsw/issues/156 and was tested with iob_sync example in iob_uart

Subblocks with 'instantiate = False' don't propagate clk interfaces to top

---

py2hwsw/lib/hardware/iob_csrs/iob_csrs.py
py2hwsw/lib/hardware/iob_csrs/scripts/csr_classes.py
py2hwsw/lib/hardware/iob_csrs/scripts/reg_gen.py
py2hwsw/lib/iob_system/iob_system.py
py2hwsw/lib/peripherals/iob_uart/iob_uart.py
py2hwsw/scripts/iob_core.py
py2hwsw/scripts/iob_license.py
py2hwsw/scripts/ipxact_gen.py

- Rename 'iob_csr.py' to 'csr_classes.py'. Resolves #173
- Small fix in ipxact_gen.
- Add 'license' attribute to iob_core. Include in IP-XACT. See af1ccf1 for details.

Rename csr script; Fix ipxact; Add `license` attribute.

---

py2hwsw/lib/hardware/arith_logic/counter/iob_modcnt/iob_modcnt.py
py2hwsw/lib/hardware/buses/iob_fifo2axis/hardware/src/iob_fifo2axis.v
py2hwsw/lib/peripherals/iob_axistream_in/hardware/simulation/src/iob_axistream_in_tb.v
py2hwsw/lib/peripherals/iob_axistream_in/iob_axistream_in.py
py2hwsw/lib/peripherals/iob_axistream_out/iob_axistream_out.py

- add testbench for axistream in and axistream out cores
- this tests AXIS IO
- run test with:
```bash
cd py2hwsw/lib;
nix-shell --run "make sim-run CORE=iob_axistream_in"
```
- minor fixes for other cores:
- modcnt: register portmap
- fifo2axis: register portmap include

feat(axis): add axistream in / axistream out tb

---

py2hwsw/lib/hardware/buses/iob_axis2ahb/hardware/simulation/src/iob_axis2ahb_tb.v
py2hwsw/lib/hardware/buses/iob_axis2ahb/hardware/src/iob_axis2ahb.v
py2hwsw/lib/hardware/buses/iob_axis2ahb/iob_axis2ahb.py
py2hwsw/lib/hardware/memories/iob_ahb_ram/hardware/src/AHB2MEM.v
py2hwsw/lib/hardware/memories/iob_ahb_ram/iob_ahb_ram.py
py2hwsw/py2hwsw_document/document/tsrc/if_gen.tex
py2hwsw/scripts/if_gen.py

- add AHB interface support
- axis2ahb converter with testbench, check with:
```bash
cd py2hwsw/lib;
nix-shell --run "make sim-run CORE=iob_axis2ahb"
```
- example ahb-lite ram

feat(ahb): add ahb interface support, axis2ahb with testbench, example ahb-lite ram

---

py2hwsw/lib/hardware/buses/iob_axis2ahb/hardware/simulation/src/iob_axis2ahb_tb.v
py2hwsw/lib/hardware/buses/iob_axis2ahb/hardware/src/iob_axis2ahb.v
py2hwsw/lib/hardware/buses/iob_axis2ahb/iob_axis2ahb.py

- use resp signal to detect ERROR in accesses
- add busy output to axis2ahb to check for state:
- can also be used to detect terminated transfers before expected (without tlast)

fix(ahb): use resp signal, add busy to converter

---

py2hwsw/lib/hardware/iob_csrs/scripts/csr_gen.py

- add addr argument for software code for regfile registers
- addr argument was only previously being added in `iob_core_csrs.h`, was missing in `iob_core_csrs.c`

fix(csrs): add addr argument for regfiles

---

py2hwsw/lib/hardware/iob_csrs/iob_csrs.py
py2hwsw/lib/hardware/iob_csrs/scripts/csr_gen.py

- update csrs to use instantiator version by default, fallback do py2hwsw version.
- With this change, a core with `"version": "ab.cd"` that instantiates a `iob_csrs` subblock, generates a `iob_[CORE]_csrs` with `"version": "ab.cd"`.
- Previously, the `iob_[CORE]_csrs` had `"version": PY2HWSW_VERSION`

fix(csrs): use instantiator version by default

---

py2hwsw/lib/hardware/basic_tests/iob_csrs_demo/iob_csrs_demo.py
py2hwsw/lib/hardware/iob_csrs/scripts/csr_gen.py

- fix software addressing for noauto regfiles: used address accounts for register n_bits
- fix case to support log2n_items string independent of n_bits type
- add test case to csrs_demo with regfile using param as log2n_items

fix(csrs): address noauto regfiles, test demo

---

py2hwsw/lib/hardware/basic_tests/iob_csrs_demo/iob_csrs_demo.py
py2hwsw/lib/hardware/iob_csrs/scripts/csr_gen.py
py2hwsw/lib/hardware/iob_csrs/scripts/fifos.py

- RW regs with wen width 1
- remove sufix `_i` from `byte_aligned` internal wires
- fix R register logic: remove unnecessary register enable
- fix RW register logic register enable on CSR write access or `wen` from core
- fix auto register csrs port names
- add example of RW register with multiple bits (to show correct `wen` generation)

fix(csrs): improve generated csrs logic

---

py2hwsw/lib/hardware/basic_tests/iob_and/iob_and.py
py2hwsw/lib/hardware/iob_csrs/iob_csrs.py
py2hwsw/lib/hardware/iob_csrs/scripts/csr_classes.py
py2hwsw/scripts/fsm_gen.py
py2hwsw/scripts/interfaces.py
py2hwsw/scripts/iob_base.py
py2hwsw/scripts/iob_comb.py
py2hwsw/scripts/iob_conf.py
py2hwsw/scripts/iob_core.py
py2hwsw/scripts/iob_fsm.py
py2hwsw/scripts/iob_license.py
py2hwsw/scripts/iob_port.py
py2hwsw/scripts/iob_python_parameter.py
py2hwsw/scripts/iob_signal.py
py2hwsw/scripts/iob_snippet.py
py2hwsw/scripts/iob_wire.py
py2hwsw/scripts/user_api/api.py

initial short notation implementation for the classes:
Other tasks:
- update `create_from_text()` methods into: `short_notation` -> `dictionary` -> `create_from_dict()` pipeline

wip(notation): Implement short notation for py2 classes

---

py2hwsw/scripts/py2hwsw_shell.py

- Add `show()` command in py2hwsw_shell.
Usage `show("<lib_core_name>")` to print the code of the corresponding lib core's .py or .json file.
- Auto-import lib cores into py2hwsw_shell
We can now run `help(iob_and)` and call the constructor for that class:
`my_obj = iob_and(width=8)`

Add show() command in py2hwsw_shell; Import lib cores into py2hwsw_shell

---

py2hwsw/lib/hardware/registers/iob_reg/iob_reg.py

This PR uses iob_reg as an example, since it is a basic module that needs the `clk_en_rst` bus, and is a dependency for many other lib modules.
See `iob_reg` ports list for the most up-to-date example of a port/bus declaration using dictionaries: https://github.com/arturum1/py2hwsw/blob/bus_example/py2hwsw/lib/hardware/registers/iob_reg/iob_reg.py#L102-L120
(For now), this syntax is similar to the one in the 'Buses' codeshare.
Iob_reg currently has 3 ports:
- 'clk_en_rst_s' port (bus)
- 'data_i' port (wire)
- 'data_o' port (wire)
Example taken from PR https://github.com/IObundle/py2hwsw/pull/366

Example module that uses a bus

---

py2hwsw/lib/hardware/arith_logic/iob_prng/iob_prng.py
py2hwsw/src/block_gen.py
py2hwsw/src/iob_base.py
py2hwsw/src/iob_bus.py
py2hwsw/src/iob_comb.py
py2hwsw/src/iob_conf.py
py2hwsw/src/iob_core.py
py2hwsw/src/iob_fsm.py
py2hwsw/src/iob_globals.py
py2hwsw/src/iob_instance.py
py2hwsw/src/iob_interface.py
py2hwsw/src/iob_license.py
py2hwsw/src/iob_module.py
py2hwsw/src/iob_parameter.py
py2hwsw/src/iob_port.py
py2hwsw/src/iob_portmap.py
py2hwsw/src/iob_snippet.py
py2hwsw/src/iob_wire.py

This PR has no functional code changes. The setup/build behavior has not changed.
- Refactor py2hwsw code
Move methods, that were previously outside classes, to inside the corresponding classes as @staticmethods.
As discussed, having these methods inside the classes allows py2hwsw_shell to import just the class.
The user can view all the class's methods by typing `help(<class_name>)`.
- Improved iob_core docstrings in commit b28fc3136e4f8613e4a83dbefc49baff2b029ad0.
Type `help(iob_core)` to view the new docstrings.

Refactor py2hwsw scripts; Improve docstrings.

---

py2hwsw/lib/iob_system/hardware/fpga/quartus/iob_cyclonev_gt_dk/board.mk
py2hwsw/lib/iob_system/hardware/fpga/vivado/iob_aes_ku040_db_g/board.tcl
py2hwsw/scripts/iob_base.py
py2hwsw/scripts/iob_core.py

- Improve `_remove_duplicate_sources()` method.
New method supports multiple levels of subfolders to check for and remove duplicate sources.
This fixes failing ghactions tests in https://github.com/IObundle/iob-soc/pull/1025
- Remove 'iob_reg_a' from fpga dependencies.
The 'iob_reg_a' module is no longer specific to the fpga boards. Now it is used by the base iob_system (in hardware/src/).

Improve `_remove_duplicate_sources()` method. 

---

.gitmodules

As suggested in: https://stackoverflow.com/a/50299434/11442904
This change will allow users to clone the repository recursively via the HTTPS URL without being authenticated with a GitHub account, like so:
```Bash
git clone https://github.com/IObundle/py2hwsw.git --recurse-submodules
```
Developers may want to configure their git client to automatically replace HTTPS URLs with SSH ones, using the following command:
```Bash
git config --global url."git@github.com:".insteadOf "https://github.com/"
```
This allows developers to keep using SSH keys for authentication, and avoids having to type account credentials when handling submodules.

feat(submodules): Use HTTPS URL instead of SSH.
